### ISSUE TITLE
Divided by zero error in LMG drill

### ISSUE THREAD

**Issue by HeliceWolf** [Cenwulf/A3RifleRange#7]
In LMG drill every time a target goes up i receive an error. Here a screenshot
https://steamuserimages-a.akamaihd.net/ugc/954082741550152581/91308EE53E9BE4EF61259B9025387A69C057A05B/

**Comment by Cenwulf** [comment]
The LMG range should have 3 targets sitting side by side at each distance rather than just the one. That bit of code that’s throwing the error is supposed to force them all to act as a single target for the purposes of hit detection.

My bad, I’ll stick a check in to make sure that it only runs if there’s actually more than one target. I’ll also upload the correct version of the mission sqm with the correct number of targets.

Thanks very much for the report.

**Comment by Cenwulf** [comment]
New commit pushed with fixes for this issue. Give it a go, let me know if you have any more problems.

Thanks again for using the range and providing useful feedback. Enjoy!

**Comment by HeliceWolf** [comment]
hey everything seems to be ok now.  Thanks for your fast bugfix. This shooting range rocks!! Just a couple of details:

1.- Huron ammobox don't have Virtual Arsenal. I added myself in my downloaded mission to have all mods weapons we are using it. I guess it should have it because not everyone is capable off add it.

2.- In LMG drill is easy to have more than 100 shoots. With 2 digits in total score was confusing first time like... dang is the score board adding up right??

I think you should upload this mission to Workshop. It's very cool. Maybe with a little explanation how it works and a note LMG drills is in Airfield but not in SaltLake.

Thanks for your nice job. Right now we can use it and enjoy 100%

**Comment by Cenwulf** [comment]
Thanks! I'm glad you guys are enjoying it.

The LMG stuff is all a bit work-in-progress at the moment. I do plan to add an extra digit to the score columns at some point. It's a bit fiddly to do though and would mean redoing the textures for the scoreboard background so it may take me a while to get round to it.

I've stuck in some diary records explaining all the in game functions of the range and instructions for each drill. They appear in the list in the top left when you open the map in game. They'll be in the next commit coming relatively soon so keep an eye out for that.

I do plan to populate the the wiki section of the github repo and try to help people use the mission as a template to design their own rifle ranges and firing drills. It's not something I'm familiar with doing so again it'll take me a while.

**Comment by Cenwulf** [comment]
Also please fell free to post any features you'd like to see added, to the issue tracker.

I can't promise that I'll be able to accommodate everything but I'll gladly add them to the list and see what I can do.
