### ISSUE TITLE
Drill instructions won't load on dedicated

### ISSUE THREAD

**Issue by AVESUM** [Cenwulf/A3RifleRange#8]
Problem:
Drill instructions won't load to player when mission is hosted on dedicated server. (on self hosted everything works fine)
General instructions are loaded, but not specific range and drill instructions. 

How to recreate:
Start with required mods (cba, ace, acex). Join mission.

**Comment by Cenwulf** [comment]
Hi there, thanks for the report.

This may be a JIP issue. If on dedicated, do the instructions load correctly for players if they join before the mission is started?

**Comment by Cenwulf** [comment]
Ok so the function that adds the instructions should be getting added to the JIP queue and then get executed on every joining player. Not sure why that's not happening in your case.

I'll have to blow the dust off my test serve and see if I can recreate the issue.

**Comment by Cenwulf** [comment]
I wasn't able to replicate the issue but I've spotted a potential cause in that the drill instructions function wasn't checking that the player object had initialised before attempting to add the diary record entries. I've pushed the update to the master branch so please feel free to redownload.

Let me know if this solves the issue.

**Comment by AVESUM** [comment]
Thank you so much! It works like a charm!

**Comment by Cenwulf** [comment]
No problem, thanks for reporting back.
